tasks:
  - init: npm install
    command: |
      wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
      unzip FiraCode.zip -d ~/.fonts
      fc-cache -fv
      export HMR_HOST=`gp url 3000`
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode
    - github.vscode-pull-request-github

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true